admin_add:
    path:     /add
    defaults: { _controller: AdminBundle:Admin:add }
    
admin_edit:
    path:     /edit/{id}
    defaults: { _controller: AdminBundle:Admin:edit }
    requirements:
        id: \d+
    
admin_delete:
    path:     /delete/{id}
    defaults: { _controller: AdminBundle:Admin:delete }
    requirements:
        id: \d+
