<?php

namespace WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdvertsAfter(\Datetime $date) 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.address', 'ad')
            ->addSelect('ad')
            ->where('a.dateStart < :date')
            ->setParameter('date', $date)
            ->orderBy('a.dateStart', 'DESC')
            ->getQuery()
        ;
        
        // On retourn seulement la query car on va paginer dans le controlleur
        return $query;
    }
    
    public function getAdvertsBefore(\Datetime $date) 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.address', 'ad')
            ->addSelect('ad')
            ->where('a.dateStart >= :date')
            ->setParameter('date', $date)
            ->orderBy('a.dateStart', 'DESC')
            ->getQuery()
        ;
        
        return $query->getResult();
    }
}
