<?php

namespace WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{ 
    public function getAdvertsFuture(\Datetime $date) 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.address', 'ad')
            ->addSelect('ad')
            ->where('a.dateEnd >= :date')
            ->orWhere('a.dateStart >= :date')
            ->setParameter('date', $date)
            ->andWhere('a.toComeUp = 0')
            ->orderBy('a.dateStart', 'ASC')
            ->getQuery()
        ;
        
        return $query->getResult();
    }
    
    public function getAdvertsToComeUp() 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.address', 'ad')
            ->addSelect('ad')
            ->where('a.toComeUp = 1')
            ->orderBy('a.dateStart', 'ASC')
            ->getQuery()
        ;
        
        return $query->getResult();
    }
    
    public function getAdvertsCategory(\Datetime $date, $category) 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.address', 'ad')
            ->addSelect('ad')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->where('a.dateEnd >= :date')
            ->orWhere('a.dateStart >= :date')
            ->setParameter('date', $date)
            ->andWhere('a.toComeUp = 0')
            ->andWhere('c.name = :category')
            ->setParameter('category', $category)
            ->orderBy('a.dateStart', 'ASC')
            ->getQuery()
        ;
        
        return $query->getResult();
    }
    
    public function getAdvertsCategoryToComeUp($category) 
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.address', 'ad')
            ->addSelect('ad')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->where('a.toComeUp = 1')
            ->andWhere('c.name = :category')
            ->setParameter('category', $category)
            ->orderBy('a.dateStart', 'ASC')
            ->getQuery()
        ;
        
        return $query->getResult();
    }
       
}
