website_homepage:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }
    
website_access_bars:
    path:     /access_bars.html
    defaults: { _controller: WebsiteBundle:Website:access_bars }
    
website_relation_aide:
    path:     /relation_aide.html
    defaults: { _controller: WebsiteBundle:Website:relation_aide }
    
website_sophrologie:
    path:     /sophrologie.html
    defaults: { _controller: WebsiteBundle:Website:sophrologie }
    
website_mon_approche:
    path:     /mon_approche.html
    defaults: { _controller: WebsiteBundle:Website:mon_approche }
    
website_contact:
    path:     /contact.html
    defaults: { _controller: WebsiteBundle:Website:contact }
    
website_events_old:
    path:     /events_old.html
    defaults: { _controller: WebsiteBundle:Website:events_old }
