website_homepage:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }
    
website_access_bars:
    path:     /access_bars
    defaults: { _controller: WebsiteBundle:Website:access_bars }
    
website_relation_aide:
    path:     /relation_aide
    defaults: { _controller: WebsiteBundle:Website:relation_aide }
    
website_sophrologie:
    path:     /sophrologie
    defaults: { _controller: WebsiteBundle:Website:sophrologie }
    
website_mon_approche:
    path:     /mon_approche
    defaults: { _controller: WebsiteBundle:Website:mon_approche }
    
website_contact:
    path:     /contact
    defaults: { _controller: WebsiteBundle:Website:contact }
    
website_events_old:
    path:     /events_old
    defaults: { _controller: WebsiteBundle:Website:events_old }
