website_homepage:
    path:     /
    defaults: { _controller: WebsiteBundle:Website:index }
    
website_access_bars:
    path:     /access_bars.html
    defaults: { _controller: WebsiteBundle:Website:accessBars }
    
website_relation_aide:
    path:     /relation_aide.html
    defaults: { _controller: WebsiteBundle:Website:relationAide }
    
website_sophrologie:
    path:     /sophrologie.html
    defaults: { _controller: WebsiteBundle:Website:sophrologie }
    
website_mon_approche:
    path:     /mon_approche.html
    defaults: { _controller: WebsiteBundle:Website:monApproche }
    
website_contact:
    path:     /contact.html
    defaults: { _controller: WebsiteBundle:Website:contact }
