# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
                    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: in_memory
            form_login:
                login_path : login
                check_path: login_check
            logout:
                path: logout
                target: /
      
                    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

